project:
  type: website

website:
  # title: "Finding your dream home"
  navbar:
    left:
      - href: index.ipynb
        text: Where to live
      - href: about.ipynb
        text: About

format:
  html:
    theme: flatly
    css: styles.css
    toc: false



