project:
  type: website

website:
  title: "Picking where to live"
  navbar:
    left:
      - href: index.ipynb
        text: Find your place
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



